
batch_size: 1

data:
  dataset: ifw_velocity_inr
  dataset_path: /home/intern/spygeorgoulas/thesis-metanets/scalegmn/data/gram_ifw_4x64_300k_rwi_pth_splitted
  target_npz_dir: /home/intern/spygeorgoulas/thesis-metanets/neural-fields-3d/data/ifw
  layer_layout: [4, 64, 64, 64, 64, 3]
  return_path: true #becareful
  node_pos_embed: &node_pos_embed True
  edge_pos_embed: &edge_pos_embed False
  #split_path: null
  #image_size: [1, 1]

inr_model:
  w0: 80.0

train_args:
  seed: 0
  num_epochs: 300000
  eval_every: 1000
  #val_acc_threshold: 0.1
  #loss: mse
  #train_query_batch_size: 10000
  eval_chunk_size: 2048 #4096
  train_eval_num_batches: 20

scalegmn_args:
  d_in_v: &d_in_v 1  # initial dimension of input nn bias
  d_in_e: &d_in_e 1  # initial dimension of input nn weights
  d_hid: &d_hid 32  # hidden dimension
  num_layers: 2 # number of gnn layers to apply
  direction: bidirectional #forward
  equivariant: True
  symmetry: sign  # symmetry
  jit: False # prefer compile - compile gnn to optimize performance
  compile: False # compile gnn to optimize performance
  out_scale: 0.01
  gnn_skip_connections: True
  concat_mlp_directions: False  # only for bidirectional: apply an MLP before concatenating the forward and backward directions
  reciprocal: True
  node_pos_embed: *node_pos_embed  # use positional encodings
  edge_pos_embed: *edge_pos_embed  # use positional encodings

  graph_init:
    d_in_v: *d_in_v
    d_in_e: *d_in_e
    project_node_feats: True
    project_edge_feats: True
    d_node: *d_hid
    d_edge: *d_hid
    
  positional_encodings:
    final_linear_pos_embed: False
    sum_pos_enc: False
    po_as_different_linear: False
    equiv_net: False
    # args for the equiv net option.
    sum_on_io: True
    equiv_on_hidden: True
    num_mlps: 3
    layer_equiv_on_hidden: False

  gnn_args:
    d_hid: *d_hid
    message_fn_layers: 1
    message_fn_skip_connections: False
    update_node_feats_fn_layers: 1
    update_node_feats_fn_skip_connections: False
    update_edge_attr: True
    dropout: 0.1
    dropout_all: True  # False: only in between the gnn layers, True: + all mlp layers
    update_as_act: False
    update_as_act_arg: sum
    mlp_on_io: True

    msg_equiv_on_hidden: True
    upd_equiv_on_hidden: True
    layer_msg_equiv_on_hidden: False
    layer_upd_equiv_on_hidden: False
    msg_num_mlps: 3
    upd_num_mlps: 3
    pos_embed_msg: False
    pos_embed_upd: False
    layer_norm: False
    aggregator: add
    sign_symmetrization: False

  mlp_args:
    d_k: [ *d_hid ]
    activation: silu
    dropout: 0.
    final_activation: identity
    batch_norm: False
    layer_norm: True
    bias: True
    skip: False

optimization:
  clip_grad: True
  clip_grad_max_norm: 10.0
  optimizer_name: AdamW
  optimizer_args:
    lr: 0.001
    weight_decay: 0.001
  scheduler_args: {}

num_workers: 8
#log_n_imgs: 0
#save_best_model: true
# best_model_path: /home/intern/spygeorgoulas/thesis-metanets/scalegmn/checkpoints/best_scalegmn_gram_iclr.pt
output_dir: /home/intern/spygeorgoulas/thesis-metanets/scalegmn/outputs/gram_velocity_scalegmn_run_jul_2026

wandb: true
wandb_args:
  project: iclr_gram_2026
  entity: mscai-spygeorgoulas
  #name: gram_ifw